name: "🏙️ 3D City Contributions"

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:
  workflow_call:

jobs:
  generate-3d-city:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D contribution city
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Push to branch `city-3d`
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: city-3d
          publish_dir: ./profile-3d-contrib
          destination_dir: profile-3d-contrib
          commit_message: "🏙️ Update 3D city"
