name: "🐍 Generate Snake"

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            snake-output/snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to branch snake-output
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: snake-output
          publish_dir: ./snake-output
          commit_message: "🐍 Update snake"
