name: TryHackMe Update Badge
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  tryhackme-badge-update:
    name: Update this repo's tryhackme badge with the latest tryhackme image badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "thesirix"
          use_static_image: false
          user_public_id: "69de1facc23d0ac598079f59"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
