name: "🚀 Update All"

on:
  workflow_dispatch:

jobs:
  snake:
    name: "🐍 Snake"
    uses: ./.github/workflows/snake.yml
    secrets: inherit

  weather:
    name: "🌤️ Weather"
    uses: ./.github/workflows/weather.yml
    secrets: inherit

  city-3d:
    name: "🏙️ 3D City"
    uses: ./.github/workflows/3d-city.yml
    secrets: inherit
