name: "🚀 Update All"

on:
  workflow_dispatch:

jobs:
  snake:
    name: "🐍 Snake"
    uses: ./.github/workflows/Snake.yml
    secrets: inherit

  weather:
    name: "🌤️ Weather"
    uses: ./.github/workflows/Weather.yml
    secrets: inherit

  city-3d:
    name: "🏙️ 3D City"
    uses: ./.github/workflows/3d_city.yml
    secrets: inherit

  tryhackme:
    name: "🔐 TryHackMe"
    uses: ./.github/workflows/tryhackme.yml
    secrets: inherit
