name: "🌤️ Weather Forecast"

on:
  schedule:
    - cron: "27 * * * *"
  workflow_dispatch:
  workflow_call:

jobs:
  update-weather:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate weather SVG & update README
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: python3 scripts/weather.py

      - name: Commit & push
        run: |
          if git diff --exit-code -- README.md assets/weather.svg; then
            echo "No changes to commit."
            exit 0
          else
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add README.md assets/weather.svg
            git commit -m "🌤️ Update weather forecast"
            git pull --rebase origin main
            git push origin main
          fi
